### ISSUE TITLE
Large margin on left reacts and hides dock

### ISSUE THREAD

**Issue by horga83** [RensAlthuis/workspaces-to-dock#3]
###Linux Distribution version
Arch

###Gnome Shell version
3.38.1

###Xorg or Wayland (or both)
Xorg

###Extension version or branch

###Description of the problem
Large margin on left side.  Cannot have any window close to the dock as it hides.  In other words there is a large margin on the left, seems like almost the width of the dock where it reacts and hides itself.

###Steps to reproduce the problem

**Comment by RensAlthuis** [comment]
Yep, you were right, thanks. 
The position calculations for dock changed with 3.38, I forgot to update it for the intellihide hitbox. It's fixed now.
