### ISSUE TITLE
Application icons do not display

### ISSUE THREAD

**Issue by horga83** [RensAlthuis/workspaces-to-dock#4]
###Linux Distribution version
Arch

###Gnome Shell version
3.38.1

###Xorg or Wayland (or both)
xorg

###Extension version or branch

###Description of the problem
Running application icons do not show on the bottom of their respective workspace.
Last bug I promise:-)

###Steps to reproduce the problem

**Comment by RensAlthuis** [comment]
Haha no worries, I don't mind fixing these issues, just keep on posting them!
Also this was because I commented out a line accidentally... wooooops
