### ISSUE TITLE
Not showing live terminal output

### ISSUE THREAD

**Issue by papampi** [RensAlthuis/workspaces-to-dock#6]
###Linux Distribution version: Ubuntu 20.10

###Gnome Shell version: 3.38.1

###Xorg or Wayland (or both): Xorg

###Extension version or branch: RensAlthuis:Master

###Description of the problem: 
It used to show live terminal in dock when dock is set to not hide, shows other live windows like videos or chrome web pages but not terminal

###Steps to reproduce the problem
Open a terminal and run a tail command, when go to other workspace the terminal in dock not scrolls and not shows terminal live output.

**Comment by RensAlthuis** [comment]
I can't reproduce this, what terminal emulator are you using?

**Comment by papampi** [comment]
Gnome-terminal, Terminus and Terminator not showing live but Xterm and QTerminal are showing live output in dock

**Comment by RensAlthuis** [comment]
As far I can tell this is not an issue with the extension. For performance reasons those terminals don't render anything if they are not on screen. The only way to fix this is by forcing those application to think they are on screen, I don't think that is a good idea. Wouldn't know how to do that anyway.
